#!/bin/sh

export GOOSE_PROVIDER=openrouter
export GOOSE_PLANNER_MODEL=anthropic/claude-sonnet-4.6
export GOOSE_MODEL=deepseek/deepseek-v4-flash
export GOOSE_MOIM_MESSAGE_FILE=${PWD}/goose/goose_moim.md
goose "${@}"